In [52]:
from subgrounds.subgrounds import Subgrounds
from subgrounds.plotly_wrappers import Bar, Figure

import pandas as pd
import plotly.express as px
import requests


# initialize Subgrounds object
sg = Subgrounds()

# load livepeer subgraph
lpt = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/livepeer/livepeer')

# define FieldPaths
transcoders = lpt.Query.transcoders
delegators = lpt.Query.delegators

In [44]:
top_by_stake = transcoders(
    orderBy=transcoders.totalStake,
    orderDirection='desc',
    first=350,
    where=[
        transcoders.active==True
    ]
)


# stake and volume can be pulled directly 
leaderboard = sg.query_df([
    top_by_stake.id,
    top_by_stake.totalStake,
    top_by_stake.totalVolumeETH,
    top_by_stake.totalVolumeUSD
])

leaderboard

,transcoders_id,transcoders_totalStake,transcoders_totalVolumeETH,transcoders_totalVolumeUSD
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2.516184e+06,8.001220,1516.763581
1,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,1.252157e+06,0.722895,1990.434657
2,0x525419ff5707190389bfb5c87c375d710f5fcb0e,9.233017e+05,21.328402,53037.759233
3,0x4ff088ac5422f994486663ff903b040692797168,7.841820e+05,0.650195,2203.164261
4,0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b,7.284690e+05,3.114552,6065.571979
...,...,...,...,...
95,0x44c98af5da6a31c422ee5eed18d53986dd9bc01e,2.870000e+01,0.000000,0.000000
96,0xa408138c3c75c927b8614a24a39de02ffd71405f,2.773960e+01,0.729165,1905.940988
97,0xb3ec176da90524ae3ea530caca4d8afc84f10c09,2.728724e+01,0.909318,3069.084897
98,0x3a025488a37fecdb6ca8a4cbd72ba87a919d8bf3,2.611006e+01,0.000000,0.000000
99,0x5b5079b69a3f8dc07ca05ee301e39a08a002def3,2.600000e+01,1.550896,4364.546168

In [45]:
# call_ratio

# filter to latest 30 eligible rounds
active_pools = top_by_stake.pools(
    orderBy=top_by_stake.pools.round.id,
    orderDirection='desc',
    first=30
)

pool_rewards = sg.query_df([
    top_by_stake.id,
    active_pools.round.id,
    active_pools.rewardTokens
])

pool_rewards[:30]

,transcoders_id,transcoders_pools_round_id,transcoders_pools_rewardTokens
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2466,1092.954931
1,0x9c10672cee058fd658103d90872fe431bb6c0afa,2465,1095.192757
2,0x9c10672cee058fd658103d90872fe431bb6c0afa,2464,1097.254215
3,0x9c10672cee058fd658103d90872fe431bb6c0afa,2463,1099.504771
4,0x9c10672cee058fd658103d90872fe431bb6c0afa,2462,1101.620111
5,0x9c10672cee058fd658103d90872fe431bb6c0afa,2461,1103.754165
6,0x9c10672cee058fd658103d90872fe431bb6c0afa,2460,1105.950452
7,0x9c10672cee058fd658103d90872fe431bb6c0afa,2459,1108.443982
8,0x9c10672cee058fd658103d90872fe431bb6c0afa,2458,NaN
9,0x9c10672cee058fd658103d90872fe431bb6c0afa,2457,1113.404995
10,0x9c10672cee058fd658103d90872fe431bb6c0afa,2456,1115.862865
11,0x9c10672cee058fd658103d90872fe431bb6c0afa,2455,1118.094534
12,0x9c10672cee058fd658103d90872fe431bb6c0afa,2454,1120.333028
13,0x9c10672cee058fd658103d90872fe431bb6c0afa,2453,1122.584665
14,0x9c10672cee058fd658103d90872fe431bb6c0afa,2452,1124.795351
15,0x9c10672cee058fd658103d90872fe431bb6c0afa,2451,1127.031183
16,0x9c10672cee058fd658103d90872fe431bb6c0afa,2450,NaN
17,0x9c10672cee058fd658103d90872fe431bb6c0afa,2449,1130.990539
18,0x9c10672cee058fd658103d90872fe431bb6c0afa,2448,1133.252525
19,0x9c10672cee058fd658103d90872fe431bb6c0afa,2447,1136.516296
20,0x9c10672cee058fd658103d90872fe431bb6c0afa,2446,1138.733742
21,0x9c10672cee058fd658103d90872fe431bb6c0afa,2445,1140.940880
22,0x9c10672cee058fd658103d90872fe431bb6c0afa,2444,1143.118606
23,0x9c10672cee058fd658103d90872fe431bb6c0afa,2443,1145.320943
24,0x9c10672cee058fd658103d90872fe431bb6c0afa,2442,1147.468999
25,0x9c10672cee058fd658103d90872fe431bb6c0afa,2441,1150.205981
26,0x9c10672cee058fd658103d90872fe431bb6c0afa,2440,1152.388006
27,0x9c10672cee058fd658103d90872fe431bb6c0afa,2439,1154.702981
28,0x9c10672cee058fd658103d90872fe431bb6c0afa,2438,1156.824850
29,0x9c10672cee058fd658103d90872fe431bb6c0afa,2437,1159.146494

In [46]:
pool_rewards = pool_rewards.groupby('transcoders_id').apply(lambda x: x.notnull().mean())
pool_rewards.rename(columns={'transcoders_pools_rewardTokens':'call_ratio'}, inplace=True)
pool_rewards

,transcoders_id,transcoders_pools_round_id,call_ratio
transcoders_id,,,
0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38,1.0,1.0,0.000000
0x02b6aac33a397aaadee5227c70c69bb97f2cc529,1.0,1.0,0.000000
0x08f10d03a0cf7a9eaddc7eacd4cf135a07a0feff,1.0,1.0,0.000000
0x0d5a6601942bf92e7b259bfc6b56009e6a1c0ad2,1.0,1.0,0.000000
0x0fc80afb7876f579f1fb1c4d1c37cf1339038658,1.0,1.0,0.000000
...,...,...,...
0xf5a88945ce64b5648b895e05eb1edf693dde8905,1.0,1.0,0.000000
0xf63b84aaa39c4406ebf2d1e3d6acb1fb51f19dbd,1.0,1.0,0.000000
0xf7da517712844b47febe9973fb7712691fdf6e28,1.0,1.0,0.033333
0xf8ee1a8af53086b025dcc9b74a2444827d3ec64c,1.0,1.0,0.000000
0xf8fb0aef25b850dc8d8aeead92eb64a3010795a0,1.0,1.0,0.000000

In [47]:
# adjustment to join w leaderboard
call_ratio = pool_rewards['call_ratio']
call_ratio = call_ratio.reset_index()
call_ratio

                                transcoders_id  call_ratio
0   0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38    0.000000
1   0x02b6aac33a397aaadee5227c70c69bb97f2cc529    0.000000
2   0x08f10d03a0cf7a9eaddc7eacd4cf135a07a0feff    0.000000
3   0x0d5a6601942bf92e7b259bfc6b56009e6a1c0ad2    0.000000
4   0x0fc80afb7876f579f1fb1c4d1c37cf1339038658    0.000000
..                                         ...         ...
95  0xf5a88945ce64b5648b895e05eb1edf693dde8905    0.000000
96  0xf63b84aaa39c4406ebf2d1e3d6acb1fb51f19dbd    0.000000
97  0xf7da517712844b47febe9973fb7712691fdf6e28    0.033333
98  0xf8ee1a8af53086b025dcc9b74a2444827d3ec64c    0.000000
99  0xf8fb0aef25b850dc8d8aeead92eb64a3010795a0    0.000000

[100 rows x 2 columns]

In [48]:
leaderboard = pd.merge(leaderboard, call_ratio, on='transcoders_id', how='inner')
leaderboard[:5]

,transcoders_id,transcoders_totalStake,transcoders_totalVolumeETH,transcoders_totalVolumeUSD,call_ratio
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2.516184e+06,8.001220,1516.763581,0.933333
1,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,1.252157e+06,0.722895,1990.434657,1.000000
2,0x525419ff5707190389bfb5c87c375d710f5fcb0e,9.233017e+05,21.328402,53037.759233,1.000000
3,0x4ff088ac5422f994486663ff903b040692797168,7.841820e+05,0.650195,2203.164261,0.900000
4,0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b,7.284690e+05,3.114552,6065.571979,1.000000

In [49]:
# total delegators

delegators_750 = top_by_stake.delegators(
    first=750
)

top_by_delegators = sg.query_df([
    top_by_stake.id,
    delegators_750.id
])

In [50]:
ordered_delegators = top_by_delegators.groupby('transcoders_id').count().sort_values(by=['transcoders_delegators_id'], ascending=False)
ordered_delegators = ordered_delegators.reset_index()
ordered_delegators.rename(columns={'transcoders_delegators_id':'delegator_count'}, inplace=True)
ordered_delegators[:5]

                               transcoders_id  delegator_count
0  0x525419ff5707190389bfb5c87c375d710f5fcb0e              716
1  0xe9e284277648fcdb09b8efc1832c73c09b5ecf59              452
2  0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9              263
3  0x9c10672cee058fd658103d90872fe431bb6c0afa              193
4  0xd18a02647d99dc9f79afbe0f58f8353178e6141f              183

In [51]:
leaderboard = pd.merge(leaderboard, ordered_delegators, on='transcoders_id', how='inner')
leaderboard

,transcoders_id,transcoders_totalStake,transcoders_totalVolumeETH,transcoders_totalVolumeUSD,call_ratio,delegator_count
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2.516184e+06,8.001220,1516.763581,0.933333,193
1,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,1.252157e+06,0.722895,1990.434657,1.000000,263
2,0x525419ff5707190389bfb5c87c375d710f5fcb0e,9.233017e+05,21.328402,53037.759233,1.000000,716
3,0x4ff088ac5422f994486663ff903b040692797168,7.841820e+05,0.650195,2203.164261,0.900000,119
4,0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b,7.284690e+05,3.114552,6065.571979,1.000000,14
...,...,...,...,...,...,...
95,0x44c98af5da6a31c422ee5eed18d53986dd9bc01e,2.870000e+01,0.000000,0.000000,0.000000,1
96,0xa408138c3c75c927b8614a24a39de02ffd71405f,2.773960e+01,0.729165,1905.940988,0.000000,1
97,0xb3ec176da90524ae3ea530caca4d8afc84f10c09,2.728724e+01,0.909318,3069.084897,0.000000,1
98,0x3a025488a37fecdb6ca8a4cbd72ba87a919d8bf3,2.611006e+01,0.000000,0.000000,0.000000,1
99,0x5b5079b69a3f8dc07ca05ee301e39a08a002def3,2.600000e+01,1.550896,4364.546168,0.000000,2

In [53]:
# regional max score
active_transcoders = transcoders(
    where=[
        transcoders.active==True
])

addresses = sg.query_json([
    active_transcoders.id
])

addresses

[{'xa66920f9bee0490a': [{'id': '0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38'},
   {'id': '0x02b6aac33a397aaadee5227c70c69bb97f2cc529'},
   {'id': '0x08f10d03a0cf7a9eaddc7eacd4cf135a07a0feff'},
   {'id': '0x0d5a6601942bf92e7b259bfc6b56009e6a1c0ad2'},
   {'id': '0x0fc80afb7876f579f1fb1c4d1c37cf1339038658'},
   {'id': '0x104a7ca059a35fd4def5ecb16600b2caa1fe1361'},
   {'id': '0x10742714f33f3d804e3fa489618b5c3ca12a6df7'},
   {'id': '0x10b21af759129f32c6064adfb85d3ea2a8c0209c'},
   {'id': '0x10e0a91e652b05e9c7449ff457cf2e96c3037fb7'},
   {'id': '0x11b04d9a305abe978aeaddc67d9d09aaa4996090'},
   {'id': '0x1d5919ebdc911ea2f3b9f6cdc6f8df8010b36541'},
   {'id': '0x21d1130dc36958db75fbb0e5a9e3e5f5680238ff'},
   {'id': '0x22ae24c2d1f489906266609d14c4c0387909a38a'},
   {'id': '0x25fa0e2b1cd178e9ba706721313cc7cab315f520'},
   {'id': '0x2e3a21ae7cdeb48f57fcad1ce16b258d5502ac05'},
   {'id': '0x2ea8ad4e9101adbd2233a85c4e06503e7d5e1d8a'},
   {'id': '0x3018741c62246bf56f6ed6142f2527acab34524c'},
   {'id': '0x3333c47fc87b65cc7409c6a169db573247807b27'},
   {'id': '0x33b4b951c8e2a0134f6512f806acbcd90677fa5b'},
   {'id': '0x3a025488a37fecdb6ca8a4cbd72ba87a919d8bf3'},
   {'id': '0x3b28a7d785356dc67c7970666747e042305bfb79'},
   {'id': '0x3bbe84023c11c4874f493d70b370d26390e3c580'},
   {'id': '0x3e2b450c0c499d8301146367680e067cd009db93'},
   {'id': '0x41239fb65360981316fcb4a8548320d305f9496d'},
   {'id': '0x432e26fc08f236c78fd237882018a95b4c0a3d2a'},
   {'id': '0x43793ab4a56e5d4c263e6320d59072e01819b6c9'},
   {'id': '0x44c98af5da6a31c422ee5eed18d53986dd9bc01e'},
   {'id': '0x4712e01e944802613de3a0a6d23274e7e0243015'},
   {'id': '0x4a43b1d7e6227c8b0512e413f406555647ff7bdb'},
   {'id': '0x4bcc9256418b29c482596443fa5c99ae114b3351'},
   {'id': '0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc'},
   {'id': '0x4ff088ac5422f994486663ff903b040692797168'},
   {'id': '0x525419ff5707190389bfb5c87c375d710f5fcb0e'},
   {'id': '0x597ad7f7a1c9f8d0121a9e949cca7530f2b25ef6'},
   {'id': '0x599f9f49e2ef93f07dc98a89ffeeb254926a1986'},
   {'id': '0x5b5079b69a3f8dc07ca05ee301e39a08a002def3'},
   {'id': '0x5be44e23041e93cdf9bcd5a0968524e104e38ae1'},
   {'id': '0x5ccdfa9d9adef6b2960a3fdb29c5f29ad9f6f5f3'},
   {'id': '0x5d11abd838073df76e32c495f97fd3239eabb9fb'},
   {'id': '0x5ee7da5c64150b68131692c227192fb28a240e52'},
   {'id': '0x685b3cf5b8fedfddc73f3486983f9432960488ba'},
   {'id': '0x6a7e4a10fc22b8b8300c990f1bb4fd45ebffc51d'},
   {'id': '0x6c06d3246fbb77c4ad75480e03d2a0a8eaf68121'},
   {'id': '0x6cb1ce2516fb7d211038420a8cf9a843c7bd3b08'},
   {'id': '0x731808ad8b1c3d13e8972db838ada5fc6ae3c2c8'},
   {'id': '0x74ba897f65f04008d8eff364efcc54b0a20e17eb'},
   {'id': '0x750fc601b63554a0d5636f11dbbf8e66a3166889'},
   {'id': '0x76a65814b6e0fa5a3598ef6503fa1d990ec0e61a'},
   {'id': '0x77543034d85ca10942685289e374a67e21a0f531'},
   {'id': '0x78a5a644801f7f62b91f26032bc1b7976a4f6790'},
   {'id': '0x808be72cea7310f1817759be52381fe116b792b3'},
   {'id': '0x847791cbf03be716a7fe9dc8c9affe17bd49ae5e'},
   {'id': '0x84939cbda5c5a83e0f0a23204953e105a31de584'},
   {'id': '0x88e103b26e1a4ce226739d37d356b22afbfeed85'},
   {'id': '0x8ad00ef5a4323ae2a5501c3baba3788547c6dd1c'},
   {'id': '0x8ce915f5ea98aa782e373a69e19173daff5d8e59'},
   {'id': '0x8d3803ecfe86afbb25899a806b46714914b0a4b5'},
   {'id': '0x90b8b6cf5c923116273fbbee4f146ff83469a1ab'},
   {'id': '0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b'},
   {'id': '0x980998e39d29dc5a92e7403fc9cd47e68b63ad5f'},
   {'id': '0x9c10672cee058fd658103d90872fe431bb6c0afa'},
   {'id': '0x9c5874aa481b9c652d5420d65ce8becaad9ff3a7'},
   {'id': '0x9d2b4e5c4b1fd81d06b883b0aca661b771c39ea3'},
   {'id': '0x9d5611bf0dadddb4441a709141d9229d7f6b3e47'},
   {'id': '0x9d61ae5875e89036fbf6059f3116d01a22ace3c8'},
   {'id': '0x9e14de5cc84e437518c2c303c88570fe13f0ad15'},
   {'id': '0x9e48d670d2bd7300796caa6c05e3d2cc41b8cb9c'},
   {'id': '0xa20416801ac2eacf2372e825b4a90ef52490c2bb'},
   {'id': '0xa408138c3c75c927b8614a24a39de02ffd71405f'},
   {'id': '0xa6a9eb29e786b5233bd99c0ba28be882fe954a0e'},
   {'id': '0xa7c3be4eb0268dcbefbd30d8f7ac8f1a57468032'},
   {'id': '0xaafb1483c63fee231266639421dfc5bfa7970384'},
   {'id': '0xb1f024bd59815fb77506548d30d3553b8240ffd7'},
   {'id': '0xb3ec176da90524ae3ea530caca4d8afc84f10c09'},
   {'id': '0xb5164d6b780786338c52f4787abba0e4a371af4d'},
   {'id': '0xbac7744ada4ab1957cbaafef698b3c068beb4fe0'},
   {'id': '0xbdcbe92befbf36d63ec547bba5842997d77dc841'},
   {'id': '0xbe8770603daf200b1fa136ad354ba854928e602b'},
   {'id': '0xbea1956531ebffd79b6c7a41fe88480cbcff4f2b'},
   {'id': '0xcb69ffc06d3c218472c50ee25f5a1d3ca9650c44'},
   {'id': '0xcfa2a70fdf74ebda788eeb1498425ceb0630e1cb'},
   {'id': '0xd00354656922168815fcd1e51cbddb9e359e3c7f'},
   {'id': '0xd0aa1b9d0cd06cafa6af5c1af272be88c38aa831'},
   {'id': '0xd1366b85ea804cbb4493f2cc9d3d805f86bd61b2'},
   {'id': '0xd18a02647d99dc9f79afbe0f58f8353178e6141f'},
   {'id': '0xd84781e1a9b74d71ea76cda8bb9f30893bfd00d1'},
   {'id': '0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9'},
   {'id': '0xdac817294c0c87ca4fa1895ef4b972eade99f2fd'},
   {'id': '0xddab9ddfa2a5a928a19dc5c02ceb5d2d53000d4c'},
   {'id': '0xe0a4a877cd0a07da7c08dffebc2546a4713147f2'},
   {'id': '0xe3a5793d7c1d2a04a903fa1695b3e3555d6084ca'},
   {'id': '0xe3dd93281188d27762dc4d91fc90391c5210cd1d'},
   {'id': '0xe8a62ca461264b3f8066668d9ecfdab401413621'},
   {'id': '0xe9e284277648fcdb09b8efc1832c73c09b5ecf59'},
   {'id': '0xf4e8ef0763bcb2b1af693f5970a00050a6ac7e1b'},
   {'id': '0xf5a88945ce64b5648b895e05eb1edf693dde8905'},
   {'id': '0xf63b84aaa39c4406ebf2d1e3d6acb1fb51f19dbd'},
   {'id': '0xf7da517712844b47febe9973fb7712691fdf6e28'},
   {'id': '0xf8ee1a8af53086b025dcc9b74a2444827d3ec64c'},
   {'id': '0xf8fb0aef25b850dc8d8aeead92eb64a3010795a0'}]}]

In [54]:
# need alias
addresses = addresses[0]['xa66920f9bee0490a']
addresses

[{'id': '0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38'},
 {'id': '0x02b6aac33a397aaadee5227c70c69bb97f2cc529'},
 {'id': '0x08f10d03a0cf7a9eaddc7eacd4cf135a07a0feff'},
 {'id': '0x0d5a6601942bf92e7b259bfc6b56009e6a1c0ad2'},
 {'id': '0x0fc80afb7876f579f1fb1c4d1c37cf1339038658'},
 {'id': '0x104a7ca059a35fd4def5ecb16600b2caa1fe1361'},
 {'id': '0x10742714f33f3d804e3fa489618b5c3ca12a6df7'},
 {'id': '0x10b21af759129f32c6064adfb85d3ea2a8c0209c'},
 {'id': '0x10e0a91e652b05e9c7449ff457cf2e96c3037fb7'},
 {'id': '0x11b04d9a305abe978aeaddc67d9d09aaa4996090'},
 {'id': '0x1d5919ebdc911ea2f3b9f6cdc6f8df8010b36541'},
 {'id': '0x21d1130dc36958db75fbb0e5a9e3e5f5680238ff'},
 {'id': '0x22ae24c2d1f489906266609d14c4c0387909a38a'},
 {'id': '0x25fa0e2b1cd178e9ba706721313cc7cab315f520'},
 {'id': '0x2e3a21ae7cdeb48f57fcad1ce16b258d5502ac05'},
 {'id': '0x2ea8ad4e9101adbd2233a85c4e06503e7d5e1d8a'},
 {'id': '0x3018741c62246bf56f6ed6142f2527acab34524c'},
 {'id': '0x3333c47fc87b65cc7409c6a169db573247807b27'},
 {'id': '0x33b4b951c8e2a0134f6512f806acbcd90677fa5b'},
 {'id': '0x3a025488a37fecdb6ca8a4cbd72ba87a919d8bf3'},
 {'id': '0x3b28a7d785356dc67c7970666747e042305bfb79'},
 {'id': '0x3bbe84023c11c4874f493d70b370d26390e3c580'},
 {'id': '0x3e2b450c0c499d8301146367680e067cd009db93'},
 {'id': '0x41239fb65360981316fcb4a8548320d305f9496d'},
 {'id': '0x432e26fc08f236c78fd237882018a95b4c0a3d2a'},
 {'id': '0x43793ab4a56e5d4c263e6320d59072e01819b6c9'},
 {'id': '0x44c98af5da6a31c422ee5eed18d53986dd9bc01e'},
 {'id': '0x4712e01e944802613de3a0a6d23274e7e0243015'},
 {'id': '0x4a43b1d7e6227c8b0512e413f406555647ff7bdb'},
 {'id': '0x4bcc9256418b29c482596443fa5c99ae114b3351'},
 {'id': '0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc'},
 {'id': '0x4ff088ac5422f994486663ff903b040692797168'},
 {'id': '0x525419ff5707190389bfb5c87c375d710f5fcb0e'},
 {'id': '0x597ad7f7a1c9f8d0121a9e949cca7530f2b25ef6'},
 {'id': '0x599f9f49e2ef93f07dc98a89ffeeb254926a1986'},
 {'id': '0x5b5079b69a3f8dc07ca05ee301e39a08a002def3'},
 {'id': '0x5be44e23041e93cdf9bcd5a0968524e104e38ae1'},
 {'id': '0x5ccdfa9d9adef6b2960a3fdb29c5f29ad9f6f5f3'},
 {'id': '0x5d11abd838073df76e32c495f97fd3239eabb9fb'},
 {'id': '0x5ee7da5c64150b68131692c227192fb28a240e52'},
 {'id': '0x685b3cf5b8fedfddc73f3486983f9432960488ba'},
 {'id': '0x6a7e4a10fc22b8b8300c990f1bb4fd45ebffc51d'},
 {'id': '0x6c06d3246fbb77c4ad75480e03d2a0a8eaf68121'},
 {'id': '0x6cb1ce2516fb7d211038420a8cf9a843c7bd3b08'},
 {'id': '0x731808ad8b1c3d13e8972db838ada5fc6ae3c2c8'},
 {'id': '0x74ba897f65f04008d8eff364efcc54b0a20e17eb'},
 {'id': '0x750fc601b63554a0d5636f11dbbf8e66a3166889'},
 {'id': '0x76a65814b6e0fa5a3598ef6503fa1d990ec0e61a'},
 {'id': '0x77543034d85ca10942685289e374a67e21a0f531'},
 {'id': '0x78a5a644801f7f62b91f26032bc1b7976a4f6790'},
 {'id': '0x808be72cea7310f1817759be52381fe116b792b3'},
 {'id': '0x847791cbf03be716a7fe9dc8c9affe17bd49ae5e'},
 {'id': '0x84939cbda5c5a83e0f0a23204953e105a31de584'},
 {'id': '0x88e103b26e1a4ce226739d37d356b22afbfeed85'},
 {'id': '0x8ad00ef5a4323ae2a5501c3baba3788547c6dd1c'},
 {'id': '0x8ce915f5ea98aa782e373a69e19173daff5d8e59'},
 {'id': '0x8d3803ecfe86afbb25899a806b46714914b0a4b5'},
 {'id': '0x90b8b6cf5c923116273fbbee4f146ff83469a1ab'},
 {'id': '0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b'},
 {'id': '0x980998e39d29dc5a92e7403fc9cd47e68b63ad5f'},
 {'id': '0x9c10672cee058fd658103d90872fe431bb6c0afa'},
 {'id': '0x9c5874aa481b9c652d5420d65ce8becaad9ff3a7'},
 {'id': '0x9d2b4e5c4b1fd81d06b883b0aca661b771c39ea3'},
 {'id': '0x9d5611bf0dadddb4441a709141d9229d7f6b3e47'},
 {'id': '0x9d61ae5875e89036fbf6059f3116d01a22ace3c8'},
 {'id': '0x9e14de5cc84e437518c2c303c88570fe13f0ad15'},
 {'id': '0x9e48d670d2bd7300796caa6c05e3d2cc41b8cb9c'},
 {'id': '0xa20416801ac2eacf2372e825b4a90ef52490c2bb'},
 {'id': '0xa408138c3c75c927b8614a24a39de02ffd71405f'},
 {'id': '0xa6a9eb29e786b5233bd99c0ba28be882fe954a0e'},
 {'id': '0xa7c3be4eb0268dcbefbd30d8f7ac8f1a57468032'},
 {'id': '0xaafb1483c63fee231266639421dfc5bfa7970384'},
 {'id': '0xb1f024bd59815fb77506548d30d3553b8240ffd7'},
 {'id': '0xb3ec176da90524ae3ea530caca4d8afc84f10c09'},
 {'id': '0xb5164d6b780786338c52f4787abba0e4a371af4d'},
 {'id': '0xbac7744ada4ab1957cbaafef698b3c068beb4fe0'},
 {'id': '0xbdcbe92befbf36d63ec547bba5842997d77dc841'},
 {'id': '0xbe8770603daf200b1fa136ad354ba854928e602b'},
 {'id': '0xbea1956531ebffd79b6c7a41fe88480cbcff4f2b'},
 {'id': '0xcb69ffc06d3c218472c50ee25f5a1d3ca9650c44'},
 {'id': '0xcfa2a70fdf74ebda788eeb1498425ceb0630e1cb'},
 {'id': '0xd00354656922168815fcd1e51cbddb9e359e3c7f'},
 {'id': '0xd0aa1b9d0cd06cafa6af5c1af272be88c38aa831'},
 {'id': '0xd1366b85ea804cbb4493f2cc9d3d805f86bd61b2'},
 {'id': '0xd18a02647d99dc9f79afbe0f58f8353178e6141f'},
 {'id': '0xd84781e1a9b74d71ea76cda8bb9f30893bfd00d1'},
 {'id': '0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9'},
 {'id': '0xdac817294c0c87ca4fa1895ef4b972eade99f2fd'},
 {'id': '0xddab9ddfa2a5a928a19dc5c02ceb5d2d53000d4c'},
 {'id': '0xe0a4a877cd0a07da7c08dffebc2546a4713147f2'},
 {'id': '0xe3a5793d7c1d2a04a903fa1695b3e3555d6084ca'},
 {'id': '0xe3dd93281188d27762dc4d91fc90391c5210cd1d'},
 {'id': '0xe8a62ca461264b3f8066668d9ecfdab401413621'},
 {'id': '0xe9e284277648fcdb09b8efc1832c73c09b5ecf59'},
 {'id': '0xf4e8ef0763bcb2b1af693f5970a00050a6ac7e1b'},
 {'id': '0xf5a88945ce64b5648b895e05eb1edf693dde8905'},
 {'id': '0xf63b84aaa39c4406ebf2d1e3d6acb1fb51f19dbd'},
 {'id': '0xf7da517712844b47febe9973fb7712691fdf6e28'},
 {'id': '0xf8ee1a8af53086b025dcc9b74a2444827d3ec64c'},
 {'id': '0xf8fb0aef25b850dc8d8aeead92eb64a3010795a0'}]

In [57]:
score_df = pd.DataFrame(columns=['transcoders_id', 'score'])

# 2/14-2/15 to account for pre-migration
since = '1644796800'
until = '1644883200'

for pair in addresses:
    address = pair['id']
    req = requests.get(f'https://leaderboard-serverless.vercel.app/api/aggregated_stats?orchestrator={address}&since={since}&until={until}')
    if req.json() == {}:
        temp_df = pd.DataFrame([{'transcoders_id': address, 'score': None}])
        score_df = pd.concat([score_df,temp_df])
        continue

    max_score = pd.DataFrame.from_dict(req.json()[address]).T.max().score
    temp_df = pd.DataFrame([{'transcoders_id': address, 'score': max_score}])
    score_df = pd.concat([score_df,temp_df])


score_df

                                transcoders_id     score
0   0x00803b76dc924ceabf4380a6f9edc2ddd3c90f38  0.853402
0   0x02b6aac33a397aaadee5227c70c69bb97f2cc529  0.943579
0   0x08f10d03a0cf7a9eaddc7eacd4cf135a07a0feff  0.924879
0   0x0d5a6601942bf92e7b259bfc6b56009e6a1c0ad2  0.997294
0   0x0fc80afb7876f579f1fb1c4d1c37cf1339038658  0.672729
..                                         ...       ...
0   0xf5a88945ce64b5648b895e05eb1edf693dde8905   0.63915
0   0xf63b84aaa39c4406ebf2d1e3d6acb1fb51f19dbd  0.537461
0   0xf7da517712844b47febe9973fb7712691fdf6e28   0.94607
0   0xf8ee1a8af53086b025dcc9b74a2444827d3ec64c         0
0   0xf8fb0aef25b850dc8d8aeead92eb64a3010795a0  0.914212

[100 rows x 2 columns]

In [58]:
score_df.notnull().sum()

transcoders_id    100
score             100
dtype: int64

In [59]:
leaderboard_copy = pd.merge(leaderboard, score_df, on='transcoders_id', how='inner')
leaderboard_copy

,transcoders_id,transcoders_totalStake,transcoders_totalVolumeETH,transcoders_totalVolumeUSD,call_ratio,delegator_count,score
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2.516184e+06,8.001220,1516.763581,0.933333,193,0
1,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,1.252157e+06,0.722895,1990.434657,1.000000,263,0.028626
2,0x525419ff5707190389bfb5c87c375d710f5fcb0e,9.233017e+05,21.328402,53037.759233,1.000000,716,0.999979
3,0x4ff088ac5422f994486663ff903b040692797168,7.841820e+05,0.650195,2203.164261,0.900000,119,0
4,0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b,7.284690e+05,3.114552,6065.571979,1.000000,14,0.870094
...,...,...,...,...,...,...,...
95,0x44c98af5da6a31c422ee5eed18d53986dd9bc01e,2.870000e+01,0.000000,0.000000,0.000000,1,0
96,0xa408138c3c75c927b8614a24a39de02ffd71405f,2.773960e+01,0.729165,1905.940988,0.000000,1,0.893606
97,0xb3ec176da90524ae3ea530caca4d8afc84f10c09,2.728724e+01,0.909318,3069.084897,0.000000,1,0.833032
98,0x3a025488a37fecdb6ca8a4cbd72ba87a919d8bf3,2.611006e+01,0.000000,0.000000,0.000000,1,0
99,0x5b5079b69a3f8dc07ca05ee301e39a08a002def3,2.600000e+01,1.550896,4364.546168,0.000000,2,0.973008