In [1]:
from subgrounds.subgrounds import Subgrounds
from subgrounds.plotly_wrappers import Bar, Figure

import pandas as pd
import plotly.express as px


# initialize Subgrounds object
sg = Subgrounds()

# load livepeer subgraph
lpt = sg.load_subgraph('https://api.thegraph.com/subgraphs/name/livepeer/livepeer')

# define FieldPaths
transcoders = lpt.Query.transcoders
delegators = lpt.Query.delegators

In [5]:
top_by_stake = transcoders(
    orderBy=transcoders.totalStake,
    orderDirection='desc',
    first=10
)


# stake and volume can be pulled directly 
leaderboard = sg.query_df([
    top_by_stake.id,
    top_by_stake.totalStake
]).set_index('transcoders_id')

leaderboard

                                            transcoders_totalStake
transcoders_id
0x9c10672cee058fd658103d90872fe431bb6c0afa            2.516184e+06
0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9            1.252157e+06
0x525419ff5707190389bfb5c87c375d710f5fcb0e            9.233017e+05
0x4ff088ac5422f994486663ff903b040692797168            7.841820e+05
0x942f0c28fb85ea0b50bfb76a3ecfa99861fa9b4b            7.284690e+05
0xe0a4a877cd0a07da7c08dffebc2546a4713147f2            6.424943e+05
0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc            5.444993e+05
0x731808ad8b1c3d13e8972db838ada5fc6ae3c2c8            5.117972e+05
0xd84781e1a9b74d71ea76cda8bb9f30893bfd00d1            4.195702e+05
0xdac817294c0c87ca4fa1895ef4b972eade99f2fd            3.410711e+05

In [9]:
active_pools = top_by_stake.pools(
    orderBy=top_by_stake.pools.round.id,
    orderDirection='desc',
    first=30
)

pool_rewards = sg.query_df([
    top_by_stake.id,
    active_pools.round.id,
    active_pools.rewardTokens
])

pool_rewards[:35]

,transcoders_id,transcoders_pools_round_id,transcoders_pools_rewardTokens
0,0x9c10672cee058fd658103d90872fe431bb6c0afa,2466,1092.954931
1,0x9c10672cee058fd658103d90872fe431bb6c0afa,2465,1095.192757
2,0x9c10672cee058fd658103d90872fe431bb6c0afa,2464,1097.254215
3,0x9c10672cee058fd658103d90872fe431bb6c0afa,2463,1099.504771
4,0x9c10672cee058fd658103d90872fe431bb6c0afa,2462,1101.620111
5,0x9c10672cee058fd658103d90872fe431bb6c0afa,2461,1103.754165
6,0x9c10672cee058fd658103d90872fe431bb6c0afa,2460,1105.950452
7,0x9c10672cee058fd658103d90872fe431bb6c0afa,2459,1108.443982
8,0x9c10672cee058fd658103d90872fe431bb6c0afa,2458,NaN
9,0x9c10672cee058fd658103d90872fe431bb6c0afa,2457,1113.404995
10,0x9c10672cee058fd658103d90872fe431bb6c0afa,2456,1115.862865
11,0x9c10672cee058fd658103d90872fe431bb6c0afa,2455,1118.094534
12,0x9c10672cee058fd658103d90872fe431bb6c0afa,2454,1120.333028
13,0x9c10672cee058fd658103d90872fe431bb6c0afa,2453,1122.584665
14,0x9c10672cee058fd658103d90872fe431bb6c0afa,2452,1124.795351
15,0x9c10672cee058fd658103d90872fe431bb6c0afa,2451,1127.031183
16,0x9c10672cee058fd658103d90872fe431bb6c0afa,2450,NaN
17,0x9c10672cee058fd658103d90872fe431bb6c0afa,2449,1130.990539
18,0x9c10672cee058fd658103d90872fe431bb6c0afa,2448,1133.252525
19,0x9c10672cee058fd658103d90872fe431bb6c0afa,2447,1136.516296
20,0x9c10672cee058fd658103d90872fe431bb6c0afa,2446,1138.733742
21,0x9c10672cee058fd658103d90872fe431bb6c0afa,2445,1140.940880
22,0x9c10672cee058fd658103d90872fe431bb6c0afa,2444,1143.118606
23,0x9c10672cee058fd658103d90872fe431bb6c0afa,2443,1145.320943
24,0x9c10672cee058fd658103d90872fe431bb6c0afa,2442,1147.468999
25,0x9c10672cee058fd658103d90872fe431bb6c0afa,2441,1150.205981
26,0x9c10672cee058fd658103d90872fe431bb6c0afa,2440,1152.388006
27,0x9c10672cee058fd658103d90872fe431bb6c0afa,2439,1154.702981
28,0x9c10672cee058fd658103d90872fe431bb6c0afa,2438,1156.824850
29,0x9c10672cee058fd658103d90872fe431bb6c0afa,2437,1159.146494
30,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,2466,542.485542
31,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,2465,543.596284
32,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,2464,544.619480
33,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,2463,545.736541
34,0xda43d85b8d419a9c51bbf0089c9bd5169c23f2f9,2462,546.786485